# Generated by Django 2.2.1 on 2020-02-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=128)),
                ('video_duration', models.IntegerField()),
                ('video_data', models.FileField(default='/avatars/default.png', upload_to='avatars/%Y/%m/%d')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['upload_time'],
            },
        ),
    ]
