# Generated by Django 2.2.1 on 2020-02-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_data',
            field=models.FileField(upload_to='video/%Y/%m/%d'),
        ),
    ]
