# Generated by Django 2.2.1 on 2020-02-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=128)),
                ('course_introduction', models.CharField(max_length=128)),
                ('course_category', models.CharField(max_length=128)),
                ('course_tag', models.CharField(max_length=32)),
                ('course_cover', models.FileField(default='/cover/default.png', upload_to='cover/%Y/%m/%d')),
                ('course_attendance', models.IntegerField(default='0')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['create_time'],
            },
        ),
    ]
