# Generated by Django 2.2.1 on 2020-02-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_attendance_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
