# Generated by Django 2.2.1 on 2020-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_attendance_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
