# Generated by Django 3.0.2 on 2020-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200125_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/default.png', upload_to='avatars/%Y/%m/%d'),
        ),
    ]
