# Generated by Django 2.2.1 on 2020-01-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200115_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groupid',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='None', max_length=254, unique=True),
        ),
    ]
