# Generated by Django 2.2.1 on 2020-01-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200122_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='siagnature',
            new_name='signature',
        ),
    ]
