# Generated by Django 2.2.1 on 2020-01-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200123_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='https://cube.elemecdn.com/3/7c/3ea6beec64369c2642b92c6726f1epng.png', upload_to='avatars/%Y/%m/%d'),
        ),
    ]
