# Generated by Django 2.2.1 on 2020-02-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_user_attendance_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attendance_course_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
